title: Mike D
description: Notes and Thoughts
baseurl: ""
url: "https://madjabal.github.io"

# Fixed markdown settings for LaTeX
markdown: kramdown
kramdown:
  math_engine: null  # This is the key change!
  input: GFM
  syntax_highlighter: rouge

theme: minima