title: Mike D
description: Notes and Thoughts
baseurl: ""
url: "https://madjabal.github.io"

markdown: kramdown
kramdown:
  math_engine: mathjax  # This is key!
  input: GFM
  syntax_highlighter: rouge

theme: minima